import "./globals.css";
import { Montserrat } from "@next/font/google";
import Link from "next/link";

const monstserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-black text-white ${monstserrat.className} mx-4 md:mx-32 my-4 md:text-md text-xs`}
      >
        <nav className="mb-8 flex items-center">
          {" "}
          <ul className="flex items-center">
            <li className="mr-8">
              <Link className="hover:bg-white p-2 rounded-md hover:text-black flex items-center" href="/">
                Home
              </Link>
            </li>
            <li className="mr-8">
              <Link className="hover:bg-white p-2 rounded-md hover:text-black flex items-center" href="/comingsoon">
                Coming Soon
              </Link>
            </li>
            <li className="mr-8">
              <Link className="hover:bg-white p-2 rounded-md hover:text-black flex items-center" href="/tvshows">
                Tv Shows
              </Link>
            </li>
           
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
